### ISSUE TITLE
php7 编译好了 可以运行了，编译yaf报错了。centos6系统。

### ISSUE THREAD

**Issue by sleepgod** [laruence/php-yaf#151]
php7 编译好了 可以运行了，编译yaf报错了。centos6系统。
/tmp/php-yaf-master/yaf.c:61: 错误：‘new_value_length’未声明(在此函数内第一次使用)
/tmp/php-yaf-master/yaf.c:61: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/tmp/php-yaf-master/yaf.c:61: 错误：所在的函数内也只报告一次。)

**Comment by laruence** [comment]
yaf  还没有支持PHP7... 稍微等待 ;)

**Comment by sleepgod** [comment]
好的，期待……
