### ISSUE TITLE
请教在使用modules中碰到一些问题

### ISSUE THREAD

**Issue by shanghai-andy** [laruence/php-yaf#153]
**ini配置**

> application.modules                             = Index,Admin

**Yaf版本**
>2.3.3

**PHP版本**
>5.5.19

---
**问题一**

在Bootstrap.php中使用
```
public function _initDefaultName(Yaf\Dispatcher $dispatcher)
{
       $dispatcher->setDefaultModule("Admin")->setDefaultController("index")->setDefaultAction("test");
}
```
**setDefaultModule** 方法设置默认模块方法无效，setDefaultController,setDefaultAction可用

**问题二**
> 访问http://xxx   默认寻找 index\index\index
> 访问http://xxx/index   默认寻找 index\index\index
> 访问http://xxx/Admin   此时Admin默认常理来说应该 寻找 Admin\index\index才对 为何在Index中寻找Admin控制器

**问题三**
> 之前翻了下前面别人了， 类似的issues问题也存在，怎么不处理了，看了下上一版本是去年10月份发布了，yaf以后还会更新吗？

**Comment by laruence** [comment]
defaultModule的意思是, 默认的module的名字是啥, 但是默认的module都会在application/下面寻找

如果你需要的是, 不在application下面寻找, 而是去modules/admin寻找, 那么你不能改变defaultModule
而是, 让他路由成admin module

比如在routeShutdown里面, $request->setModuleName("admin")就好了

**Comment by laruence** [comment]
Yaf当然更新啊, 持续更新中, 不过目前比较稳定, 不会添加什么新功能.

最近刚刚做完PHP7的支持, 但是也不涉及功能变更 :)

**Comment by shanghai-andy** [comment]
哦，明白了，谢谢。

**Comment by lagolas** [comment]
请问下
如果你需要的是, 不在application下面寻找, 而是去modules/admin寻找, 那么你不能改变defaultModule
而是, 让他路由成admin module

比如在routeShutdown里面, $request->setModuleName("admin")就好了
是怎么操作呢？
