### ISSUE TITLE
Call class/models from module in libray

### ISSUE THREAD

**Issue by famonsei** [laruence/php-yaf#155]
Hey,

And thanks for your job.

I want to use the "modules" concept and I need to call a *classModel* into another class locate in library repository but it doesn't works.

Any solution to register and autoload maybe like this :
 ```
public function _initLoader(Yaf\Dispatcher $dispatcher)
    {
    	$loader = Yaf\Loader::getInstance();
    	$loader->autoload('../modules/Paybag/models/Webapp');
    }
```
result :
```
PHP Warning:  Yaf\\Loader::autoload(): Failed opening script /var/www/api/models/Webapp.php: No such file or directory in /var/www/api/vendor/SORM/SORM.php
```
my application.ini
```
[yaf]
application.ext         = 'php'
application.view.ext    = 'phtml'
application.modules		= 'Default,Evaluation,Paybag'
application.directory       = APP_PATH
application.bootstrap       = APP_PATH'/Bootstrap.php'
application.library         = APP_PATH'/vendor'
application.dispatcher.defaultRoute     = ''
application.dispatcher.throwException   = 0
application.dispatcher.catchException   = 0
application.dispatcher.defaultModule        = 'Default'
application.dispatcher.defaultController    = 'Default'
application.dispatcher.defaultAction        = 'Index'
```
One more thing, module name is obliged to have the first letter capitalized ?

Thanks for any reponses and sorry for my bad english.

**Comment by laruence** [comment]
Hey: autoload take a classname as parameter.

if you want to load a script, you should use $loader->import()

**Comment by laruence** [comment]
and for module name, it's better use first letter capitalized.. otherwise, Yaf will do it for you..

**Comment by famonsei** [comment]
Thanks for your answer.

My library SORM.php is supposed to call un classModel() located in a module.
If I move this classModel() in root folder models no worries otherwhise SORM.php does not find it.

Thanks for your time. I realize that I'm not very good either in namespace...

**Comment by LvChengbin** [comment]
I have the same question. Some modules need to use API in other modules. I want to know how to load other modules when i need, and with my dir structure like this : 
- library
- modules
- - actions
- - controllers
- - api ( this dir is use to store api files so that other modules can call these api )

Can you help me with this ? Thanks a bunch.

**Comment by famonsei** [comment]
Hi,
Meanwhile I found another solution.
My *SORM* class/vendor allows to make multiconnexions, so a database by module.
Each model of a module is an extend of *Host* root model for remember the source. The source is stored in the construct.
```
function __construct($host = NULL)
{
    $this->setHostFrom(
        !empty($host) ? 
        strtolower($host) : 
        strtolower(\Yaf\Dispatcher::getInstance()->getRequest()->getModuleName())
    );
}
```
And I make my call like this :
```
// call entity from module Module1
$order = SORM::getOne('Module1/Order', 38);
// call entity from module Module2
$order = SORM::getOne('Module2/Order', 37);
// call entity form module where wse are
$order = SORM::getOne('Order', 36);
```

Then I added the loading modules in Bootstrap like this :
```
public function _initModule(Yaf\Dispatcher $dispatcher)
    {
        //load script for each  module
        $app = $dispatcher->getApplication();
        $modules = $app->getModules();
        foreach ($modules as $module)
        {
            // index modules located on root folder and already load
            if ('index' == strtolower($module)) continue;

            //import class from all modules
            $pathModule = $app->getAppDirectory() . '/modules/' . $module . '/models';
            $models = scandir($pathModule);
            foreach ($models as $model)
            {
                //load only class PHP (except '.', '..', etc)
                if (strstr($model, '.php'))
                    Yaf\Loader::import($pathModule . '/' . $model);
            }
        }
    }
```
If it helps you a little ...

Otherwise move your api in library if it becomes too "common" as use.
