### ISSUE TITLE
自己的分享推广，建议和体验

### ISSUE THREAD

**Issue by luisxue** [laruence/php-yaf#157]
谢谢反馈，yaf框架现在还很弱小，对项目产品的实际应用效果不是很理想，但是它应该定位成小而美的框架，真心希望可以yaf框架可以走的更远，自己会在自己的位置贡献自己的分享推广，建议和体验~
建议：0到1已经完成，1到更多需要大家一起努力~
A：问题，yaf的php扩展在Linux,mac和Windows平台的安装有N多种问题，建议官方完善论坛
      有安装板块和问题反馈列表（如小米论坛一样，Discuz有小米模板）
B：问题，应用性能（扩展的性能不用怀疑）提升等于0，即继承yafPHP扩展的PHP应用二次性能提升为零，建议官方出一个：yafPHP扩展应用二次性能提升引擎（可以借鉴各个主流的框架CI,TP,YII等）
C：兵法曰：以正和，以奇胜~（正和完善了就得出奇兵）：问题，一直没有看到yaf在PHP产品开发的优越性（是骡子是马拉出来溜达一下），建议：官方可以出个产品小demo（可以体现yaf的优越性：性能，安全，易扩展）

**Comment by wenjun1055** [comment]
没明白前两点在说啥

**Comment by kkshow** [comment]
第一个问题是说教程不够完善，安装过程中的问题可以整理成一个FAQ什么的。
第二个是觉得yaf不能上手即用？db类什么的还需要自己封装。

此外demo的话论坛上是可以下载到的。
具体访问 http://www.yafphp.com/forum.php，虽然看起来比较冷清。

**Comment by wenjun1055** [comment]
我来一个个回答吧：
第一，先看手册，安过php扩展的人肯定没有这个问题
第二，yaf定位就是一个小众化的框架，定位人群跟其他的不一样，能驾驭他的会为他的设计点赞，驾驭不了的会发疯

**Comment by wuleying** [comment]
C ->  http://weibo.com
