### ISSUE TITLE
mac安装yaf命令行下显示内存泄漏

### ISSUE THREAD

**Issue by jonnywang** [laruence/php-yaf#160]
Hello World! I am Stranger[Wed Mar 25 18:48:19 2015]  Script:  '/Users/venkman/workspace/php/yafp/htdoc/index.php'
/Users/venkman/data/soft/php-5.5.15/Zend/zend_operators.c(1979) :  Freeing 0x110AFE1F8 (6 bytes), script=/Users/venkman/workspace/php/yafp/htdoc/index.php
Last leak repeated 1 time
=== Total 2 memory leaks detected ===

**Comment by zxcvdavid** [comment]
能不能给一个很简单的重现脚本，并说明你的php版本和yaf版本。

**Comment by jonnywang** [comment]
php 5.5.15 debug
mac 10.10.2

项目就是tools下工具生成的demo

**Comment by laruence** [comment]
这个不用管, 这个不是严格意义上的"内存"泄露, PHP完成执行以后这部分内存会被妥善回收.
