### ISSUE TITLE
使用pecl安装yaf make failed，但是自己编译成功

### ISSUE THREAD

**Issue by mhsun1992** [laruence/php-yaf#166]
php version: 5.6.9
os: centos
error:
 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootcrJ0k7/yaf-2.2.9/include -I/tmp/pear/temp/pear-build-rootcrJ0k7/yaf-2.2.9/main -I/tmp/pear/temp/yaf -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_config.c  -fPIC -DPIC -o .libs/yaf_config.o
/tmp/pear/temp/yaf/yaf_config.c: 在函数‘yaf_config_zval_dtor’中:
/tmp/pear/temp/yaf/yaf_config.c:89: 错误：‘IS_CONSTANT_ARRAY’未声明(在此函数内第一次使用)
/tmp/pear/temp/yaf/yaf_config.c:89: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/tmp/pear/temp/yaf/yaf_config.c:89: 错误：所在的函数内也只报告一次。)
/tmp/pear/temp/yaf/yaf_config.c: 在函数‘yaf_config_ini_zval_persistent’中:
/tmp/pear/temp/yaf/yaf_config.c:189: 错误：‘IS_CONSTANT_ARRAY’未声明(在此函数内第一次使用)
/tmp/pear/temp/yaf/yaf_config.c: 在函数‘yaf_config_ini_zval_losable’中:
/tmp/pear/temp/yaf/yaf_config.c:227: 错误：‘IS_CONSTANT_ARRAY’未声明(在此函数内第一次使用)
make: *** [yaf_config.lo] 错误 1
ERROR: `make' failed

**Comment by laruence** [comment]
pecl稳定版不支持5.6, 你需要安装beta版本(那个修复只在beta版里包含)
