### ISSUE TITLE
php7 + yaf(php7)

### ISSUE THREAD

**Issue by cfanbo** [laruence/php-yaf#171]
In file included from /usr/local/php7/include/php/Zend/zend.h:39:0,
                 from /usr/local/php7/include/php/main/php.h:35,
                 from /home/vagrant/soft/yaf/yaf.c:22:
/usr/local/php7/include/php/Zend/zend_variables.h:111:15: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
make: *** [yaf.lo] Error 1

**Comment by laruence** [comment]
are you using the php7 branch in yaf repo?

**Comment by laruence** [comment]
can you also paste out which line trigger that error?

**Comment by cfanbo** [comment]
用的就是YAF 的PHP7分支的。
第一次没有用出现这个，后来发现有PHP7这个分支，就换成这个YAF分支，重新CONFIGURE了仍然提过 个错误

**Comment by laruence** [comment]
你把错误的部分再多贴点.  目前的这个你只截取了包含文件的信息, 没有贴出来具体是哪行出错的.

**Comment by cfanbo** [comment]
make时提示的错误如下：
[root@localhost php-yaf]# make
/bin/sh /root/soft/php-yaf/libtool --mode=compile cc  -I. -I/root/soft/php-yaf -DPHP_ATOM_INC -I/root/soft/php-yaf/include -I/root/soft/php-yaf/main -I/root/soft/php-yaf -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/soft/php-yaf/yaf.c -o yaf.lo
mkdir .libs
 cc -I. -I/root/soft/php-yaf -DPHP_ATOM_INC -I/root/soft/php-yaf/include -I/root/soft/php-yaf/main -I/root/soft/php-yaf -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/soft/php-yaf/yaf.c  -fPIC -DPIC -o .libs/yaf.o
/root/soft/php-yaf/yaf.c: In function ‘OnUpdateSeparator’:
/root/soft/php-yaf/yaf.c:59:24: warning: assignment from incompatible pointer type [enabled by default]
  YAF_G(name_separator) = new_value;
                        ^
/root/soft/php-yaf/yaf.c:60:30: error: ‘new_value_length’ undeclared (first use in this function)
  YAF_G(name_separator_len) = new_value_length;
                              ^
/root/soft/php-yaf/yaf.c:60:30: note: each undeclared identifier is reported only once for each function it appears in
/root/soft/php-yaf/yaf.c: In function ‘zm_deactivate_yaf’:
/root/soft/php-yaf/yaf.c:230:3: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [enabled by default]
   zval_ptr_dtor(&(YAF_G(modules)));
   ^
In file included from /usr/local/php7/include/php/Zend/zend.h:39:0,
                 from /usr/local/php7/include/php/main/php.h:35,
                 from /root/soft/php-yaf/yaf.c:22:
/usr/local/php7/include/php/Zend/zend_variables.h:111:15: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
make: *** [yaf.lo] Error 1

**Comment by laruence** [comment]
你绝对是使用错了分支, 
````
/** {{{ PHP_INI_MH(OnUpdateSeparator)
 */
PHP_INI_MH(OnUpdateSeparator) {
    YAF_G(name_separator) = new_value->val;
    YAF_G(name_separator_len) = new_value->len;
    return SUCCESS;
}

````
PHP7的分支的OnUpdateSeparator的代码是这样的.

**Comment by cfanbo** [comment]
果然用错了分支！唉。。

**Comment by laruence** [comment]
PHP7分支的代码在: https://github.com/laruence/php-yaf/tree/php7

**Comment by kylinDev** [comment]
我的是同一个问题，但是错误信息如下
/home/kylin/src/yaf/yaf.c:59:24: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  YAF_G(name_separator) = new_value; 
                        ^
/home/kylin/src/yaf/yaf.c:60:30: error: ‘new_value_length’ undeclared (first use in this function)
  YAF_G(name_separator_len) = new_value_length;
                              ^
/home/kylin/src/yaf/yaf.c:60:30: note: each undeclared identifier is reported only once for each function it appears in
In file included from /opt/php7/include/php/Zend/zend.h:39:0,
                 from /opt/php7/include/php/main/php.h:35,
                 from /home/kylin/src/yaf/yaf.c:22:
/home/kylin/src/yaf/yaf.c: In function ‘zm_deactivate_yaf’:
/opt/php7/include/php/Zend/zend_variables.h:110:48: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                ^
/home/kylin/src/yaf/yaf.c:230:3: note: in expansion of macro ‘zval_ptr_dtor’
   zval_ptr_dtor(&(YAF_G(modules)));
   ^
/opt/php7/include/php/Zend/zend_variables.h:100:15: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval ** {aka struct _zval_struct **}’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
Makefile:193: recipe for target 'yaf.lo' failed
make: *** [yaf.lo] Error 1

**Comment by motecshine** [comment]
你使用的是从这里 clone的主干分支么 .

3.0.5-dev 代码是这样的
```

/** {{{ PHP_INI_MH(OnUpdateSeparator)
 */
PHP_INI_MH(OnUpdateSeparator) {
	YAF_G(name_separator) = ZSTR_VAL(new_value);
	YAF_G(name_separator_len) = ZSTR_LEN(new_value);
	return SUCCESS;
}
```

而不是
```
   YAF_G(name_separator) = new_value;
```
所以你很有可能用错了分支
