### ISSUE TITLE
$request->getControllerName 返回Favicon.ico 以及/Css/

### ISSUE THREAD

**Issue by flyyang** [laruence/php-yaf#175]
RT.

在 Plugins的preDispatch方法中做路由控制。预期之外的controller name如题中描述。

**Comment by laruence** [comment]
那是因为你没把这部分请求在nginx上挡掉(静态文件请求不应该交到fpm), 那么yaf看到你请求/favicon.ico自然就按照路由解析了.

**Comment by xinxing0913** [comment]
支持一下。
