### ISSUE TITLE
yaf_response_t误写成yaf_view_t

### ISSUE THREAD

**Issue by mhsun1992** [laruence/php-yaf#177]
PHP_METHOD(yaf_controller, getResponse) 中 ：

yaf_view_t *view = zend_read_property(yaf_controller_ce, getThis(), ZEND_STRL(YAF_CONTROLLER_PROPERTY_NAME_RESPONSE), 1, NULL);
=>
yaf_response_t *response = zend_read_property(yaf_controller_ce, getThis(), ZEND_STRL(YAF_CONTROLLER_PROPERTY_NAME_RESPONSE), 1, NULL);

估计复制粘贴后没有修改yaf_view_t为yaf_response_t。
虽然值都是zval，还是在这里提一下。

**Comment by laruence** [comment]
你要不弄个PR过来?

**Comment by mhsun1992** [comment]
已PR
