### ISSUE TITLE
为啥无法在ini文件中配置route规则？

### ISSUE THREAD

**Issue by SyuTingSong** [laruence/php-yaf#179]
我用的是pecl安装的yaf 2.3.3

我试着在.ini文件里写了route的规则：

    [common]
    application.directory = APPLICATION_PATH  "/application"
    application.dispatcher.catchException = TRUE
    routes.rewrite.type="rewrite"
    routes.rewrite.match="/view/:name/:value"
    routes.rewrite.controller=index
    routes.rewrite.action=view
    [product : common]
    

然后在Bootstrap中写了：

    public function _initRoute(Yaf_Dispatcher $dispatcher) {
        $dispatcher->getRouter()->addConfig(
            Yaf_Registry::get("config")->routes
        );
    }

可是PHP却一直报这个警告：

    PHP Warning:  Yaf_Router::addConfig(): Unable to initialize route named 'rewrite' in /web/yaf_test/application/Bootstrap.php on line 29

我把Bootstrap改成：

    public function _initRoute(Yaf_Dispatcher $dispatcher) {
        $dispatcher->getRouter()->addRoute(
            'rewrite',
            new Yaf_Route_Rewrite('/view/:name/:value', array(
                'action' => 'view',
                'controller' => 'index',
            ))
        );
    }

IndexController下的viewAction方法就能正常被调用。

**Comment by laruence** [comment]
看这里的例子: http://php.net/manual/en/yaf-router.addconfig.php

thanks

**Comment by SyuTingSong** [comment]
没看出有什么实质性的差别，例子里只是把$dispatcher->getRouter()放到变量里了，然后再调用那个变量的addConfig方法。还有例子里的 __initConfig 方法里用的变量名叫`$config`，而我是用yaf_cg生成的代码，那个方法里的变量名叫arrConfig

    public function _initConfig() {
        //把配置保存起来
        $arrConfig = Yaf_Application::app()->getConfig();
        Yaf_Registry::set('config', $arrConfig);
    }

**Comment by SyuTingSong** [comment]
哦，我看出来了，原来controller和action要写在route下。

不过为啥rewrite的写法和simple的不一样？

**Comment by laruence** [comment]
simple没有route的概念啊

**Comment by SyuTingSong** [comment]
也罢，我初看的是 http://www.laruence.com/manual/yaf.routes.usage.html 的例子，这里的rewrite没有action和controller的部分，我就直接把simple的抄下来了。
