### ISSUE TITLE
Failed test with PHP 7.0.0beta2 / ZTS build (segfault)

### ISSUE THREAD

**Issue by remicollet** [laruence/php-yaf#180]
Both on i386 / x86_64.
NTS build => test suite is ok.

ZTS buid :

     TEST 16/85 [tests/016.phpt]
     ========DIFF========
     006+ company=>
     007+ Termsig=11
     006- company=>Baidu
     007- int(0)
     ========DONE========
     FAIL Check for Yaf_Session [tests/016.phpt]

**Comment by remicollet** [comment]
Hmm.. it seems I cannot reproduce it again...
Could be related when I run various simultenaous build..

**Comment by remicollet** [comment]
(gdb) run .... tests/016.php
     bool(true)
     bool(true)
     int(3)
     name=>Laruence
     age=>28
     company=>
     Program received signal SIGSEGV, Segmentation fault.
     0x0000555555680c20 in readline_shell_ub_write ()
     (gdb) bt
     #0  0x0000555555680c20 in readline_shell_ub_write ()
     #1  0x000055555585e32f in sapi_cli_ub_write ()
     #2  0x000055555575a1c4 in php_output_write ()
     #3  0x0000555555818709 in ZEND_ECHO_SPEC_CV_HANDLER ()
     #4  0x00005555557fcbfb in execute_ex ()
     #5  0x00005555557a36c6 in dtrace_execute_ex ()
     #6  0x000055555585c549 in zend_execute ()
     #7  0x00005555557b6db7 in zend_execute_scripts ()
     #8  0x0000555555746508 in php_execute_script ()
     #9  0x000055555585e0af in do_cli ()
     #10 0x000055555561cc30 in main ()

The segfault occurs in libedit library (which is very probably not thread safe)

So the segfault is probably only related to the test env. and won't affect real use case.

**Comment by laruence** [comment]
okey, thanks for the update :)
