### ISSUE TITLE
PHP7 Yaf_Session 的BUG

### ISSUE THREAD

**Issue by aayjaa** [laruence/php-yaf#182]
使用Yaf_Session设置session时，如果内容是字符串变量，action结束后，在Dispatch后session里的字符串变量内容变成当前的controller名

**Comment by laruence** [comment]
你能举个例子么? 比如?  就是我怎么能重现.

**Comment by aayjaa** [comment]
```php
class IndexController extends Yaf_Controller_Abstract {
    public function indexAction() {
		$a="abc";
		print_r("print_r session:<br/>");
		print_r(Yaf_Session::getInstance());//
		echo "<br />";
		print_r("set session:<br/>");
		Yaf_Session::getInstance()->set("abc", $a);
		print_r(Yaf_Session::getInstance());//此时abc是成功写入session的。刷新页面session abc会变成Index
    }
}
```

**Comment by laruence** [comment]
只有PHP7是吧? 我试试

**Comment by laruence** [comment]
我不能重现啊.....

**Comment by aayjaa** [comment]
![image](https://cloud.githubusercontent.com/assets/3897574/9084172/67c32e86-3ba3-11e5-9059-4f0e3029ab86.png)
o(╯□╰)o~~

**Comment by Red-wolf-s-husband** [comment]
![image](https://cloud.githubusercontent.com/assets/4018764/9085701/a6f0936a-3bb1-11e5-8e6d-f93ea60570b0.png)
我这里也不能重现，@aayjaa 你贴一下你的各种环境参数，
```
php -v
uname -a
```

**Comment by laruence** [comment]
你把你的整个项目打包吧发给我看看? 我估计是受其他地方的影响吧....

**Comment by aayjaa** [comment]
TUT 换个环境就可以了。。
应该是编译扩展的时候出错了。
![image](https://cloud.githubusercontent.com/assets/3897574/9106602/156f1486-3c54-11e5-8d75-0d193e245508.png)
