### ISSUE TITLE
rewrite路由能否支持映射到namespace下的controller

### ISSUE THREAD

**Issue by heivin** [laruence/php-yaf#183]
比如application.ini中，可以
routes.event.type="rewrite"
routes.event.match="/event/"
routes.event.route.controller="\MyNameSpace\Event"
routes.event.route.action=get

routes.event.type="rewrite"
routes.event.match="/event/test"
routes.event.route.controller="\Test\Event"
routes.event.route.action=get

**Comment by laruence** [comment]
这个我还真没试过, 你试试呗, 如果不行的话, 采用自定义路由应该可以.
